# Generated by Django 5.1.1 on 2024-10-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_smart', '0003_cobtadordata_luminosidadedata_temperaturadata_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CobtadorData',
            new_name='ContadorData',
        ),
        migrations.AlterField(
            model_name='temperaturadata',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
