# Generated by Django 5.1.1 on 2024-10-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_smart', '0004_rename_cobtadordata_contadordata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperaturadata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
